// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVifi9j4KzVIWiJBh5dplUsVou6jBJP8',
    appId: '1:373714230340:web:363bb9dd50f28034d23011',
    messagingSenderId: '373714230340',
    projectId: 'bus-tracking-application-11491',
    authDomain: 'bus-tracking-application-11491.firebaseapp.com',
    databaseURL: 'https://bus-tracking-application-11491-default-rtdb.firebaseio.com',
    storageBucket: 'bus-tracking-application-11491.appspot.com',
    measurementId: 'G-G387GFZ3F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bU2PWTn4IZBCAs82K9tipj_b1YqABSs',
    appId: '1:373714230340:android:6b22c6784201416cd23011',
    messagingSenderId: '373714230340',
    projectId: 'bus-tracking-application-11491',
    databaseURL: 'https://bus-tracking-application-11491-default-rtdb.firebaseio.com',
    storageBucket: 'bus-tracking-application-11491.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0l_VysAMURAXKbDy-klgcpc_XiJJycSw',
    appId: '1:373714230340:ios:416f65bc49f09a86d23011',
    messagingSenderId: '373714230340',
    projectId: 'bus-tracking-application-11491',
    databaseURL: 'https://bus-tracking-application-11491-default-rtdb.firebaseio.com',
    storageBucket: 'bus-tracking-application-11491.appspot.com',
    iosBundleId: 'com.example.navii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0l_VysAMURAXKbDy-klgcpc_XiJJycSw',
    appId: '1:373714230340:ios:8bc724f3f2af59bdd23011',
    messagingSenderId: '373714230340',
    projectId: 'bus-tracking-application-11491',
    databaseURL: 'https://bus-tracking-application-11491-default-rtdb.firebaseio.com',
    storageBucket: 'bus-tracking-application-11491.appspot.com',
    iosBundleId: 'com.example.navii.RunnerTests',
  );
}
